services:
  - type: web
    name: local-life-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false 